MIPChat/Controllers/MessangerController.cs
using MIPChat.DAL.Domain;
using MIPChat.DAL.UnitOfWork;
using MIPChat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MIPChat.Controllers
{

    [Authorize]
    public class MessangerController : Controller
    {

        private ChatUnitOfWork messangerData;

        public MessangerController()
        {
            messangerData = new ChatUnitOfWork();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetAllChatsForUser(Guid userId)
        {
            var chats = messangerData.Users.FindById(userId).Chats;
            return PartialView(chats);
        }



        [HttpPost]
        public ActionResult FindChat(Guid ChatID)
        {
            var chatInst = messangerData.Chats.FindById(ChatID).Messages;

            return PartialView(chatInst);

        }



        [HttpPost]
        public ActionResult GetAllUsersToChat(Guid correntUser)
        {
            var userList = messangerData.Users.FindAvailableUsersForChat(correntUser);
            return PartialView(userList);
        }


        [HttpPost]
        public ActionResult GetAllUsersToMessage(Guid userId)
        {
            dynamic existingMessagesForUser = messangerData.Users.FindById(userId).Chats.Where(u => u.Users.Count == 2);

            ICollection<User> userList = new List<User>();

            foreach (var user in messangerData.Users.FindAll())
            {
                if (!existingMessagesForUser.Contains(user))
                {
                    userList.Add(user);
                }
            }

            return PartialView(userList);
        }

        [HttpPost]
        public ActionResult CreateMessageOrChat(string name, ICollection<Guid> usersGuids)
        {
            if (usersGuids.Count >= 2)
            {
                var users = new List<User>();
                foreach (var guid in usersGuids)
                {
                    users.Add(messangerData.Users.FindById(guid));
                }

                if (users.Count == 2)
                {
                    //create messagechat
                    messangerData.Chats.Insert(new Chat() { Name = name, 
                                                                 Users = new List<User>(users), 
                                                                 ChatId = Guid.NewGuid(), 
                                                                 IsLocal = true
                                                                });
                }
                else if (users.Count > 2)
                {
                    //create chat
                    messangerData.Chats.Insert(new Chat() {  Name = name, 
                                                                  ChatId = Guid.NewGuid(), 
                                                                  IsLocal = false, 
                                                                  Users = users
                                                                });

                }
                messangerData.CommitChanges();
                //132
                return PartialView();
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        public ActionResult SendMessage(string message, Guid chatId, Guid UserSenderId)
        {
            var correntChat = messangerData.Chats.FindById(chatId);
            var correntUser = messangerData.Users.FindById(UserSenderId);

            correntChat.Messages.Add(new Message() { Content = message, 
                                                     TheTimeOfSending = DateTime.Now, 
                                                     ChatId = correntChat.ChatId, 
                                                     UserId = correntUser.UserId, 
                                                     MessageId = Guid.NewGuid() 
                                                   });
            messangerData.CommitChanges();
            return PartialView();
        }
    }
}

MIPChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MIP Software", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("MIP Messanger", "Index", "Messanger")</li>
                    <li>@Html.ActionLink("Информация?", "About", "Home")</li>
                    <li>@Html.ActionLink("Связаться?", "Contact", "Home")</li>
                    <li>
                        @Ajax.ActionLink("LogOut", "Logout", "Account", new AjaxOptions { HttpMethod = "Webmethod"} )
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>